import React from 'react';
import { TrendingUp, TrendingDown } from 'lucide-react';

export const PDFExportTemplate = ({ trades, traderName, dateRange, stats, chartImage }: any) => {
    return (
        <div className="w-[794px] bg-[#080808] text-white p-10 font-sans" id="pdf-export-root">
            {/* HEADER */}
            <div className="flex justify-between items-center pb-6 border-b border-[#00C853] mb-8">
                <div className="flex items-center gap-2">
                    <span className="text-3xl font-black text-white">ENT</span>
                    <span className="text-3xl font-black text-[#00C853]">Journal</span>
                </div>
                <div className="text-right">
                    <p className="text-xl font-bold">{traderName}</p>
                    <p className="text-sm text-gray-400">{dateRange}</p>
                </div>
            </div>

            {/* SUMMARY STATS */}
            <div className="grid grid-cols-4 gap-4 mb-8">
                {[
                    { label: 'Total Trades', value: stats.totalTrades },
                    { label: 'Win Rate', value: `${stats.winRate}%` },
                    { label: 'Total P&L', value: stats.totalPnl },
                    { label: 'Profit Factor', value: stats.profitFactor }
                ].map((stat, i) => (
                    <div key={i} className="bg-[#111111] p-4 rounded-xl border border-[rgba(255,255,255,0.05)]">
                        <p className="text-[10px] uppercase text-gray-500 font-bold mb-1">{stat.label}</p>
                        <p className="text-2xl font-black text-[#00C853]">{stat.value}</p>
                    </div>
                ))}
            </div>

            {/* EQUITY CURVE */}
            {chartImage && (
                <div className="mb-8 p-4 bg-[#111111] rounded-xl border border-[rgba(255,255,255,0.05)]">
                    <h3 className="text-sm font-bold text-gray-500 mb-2 uppercase">Equity Curve</h3>
                    <img src={chartImage} alt="Equity Curve" className="w-full rounded-lg" />
                </div>
            )}

            {/* TRADE TABLE */}
            <table className="w-full border-collapse border border-[rgba(255,255,255,0.05)]">
                <thead className="bg-[#00C853]">
                    <tr className="text-black text-left">
                        <th className="p-3 text-xs">Date</th>
                        <th className="p-3 text-xs">Pair</th>
                        <th className="p-3 text-xs">Direction</th>
                        <th className="p-3 text-xs">Entry</th>
                        <th className="p-3 text-xs">Exit</th>
                        <th className="p-3 text-xs">P&L</th>
                        <th className="p-3 text-xs">Session</th>
                        <th className="p-3 text-xs">Result</th>
                    </tr>
                </thead>
                <tbody>
                    {trades.map((trade: any, i: number) => (
                        <tr key={i} className={i % 2 === 0 ? 'bg-[#0d0d0d]' : 'bg-[#111111]'}>
                            <td className="p-3 text-xs">{trade.date}</td>
                            <td className="p-3 text-xs">{trade.pair}</td>
                            <td className="p-3 text-xs">
                                <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${trade.dir === 'Long' ? 'bg-[rgba(0,200,83,0.2)] text-[#00C853]' : 'bg-[rgba(239,68,68,0.2)] text-red-500'}`}>
                                    {trade.dir}
                                </span>
                            </td>
                            <td className="p-3 text-xs">{trade.entry}</td>
                            <td className="p-3 text-xs">{trade.exit}</td>
                            <td className="p-3 text-xs">{trade.pnl}</td>
                            <td className="p-3 text-xs">{trade.session}</td>
                            <td className={`p-3 text-xs font-bold ${trade.result === 'win' ? 'text-[#00C853]' : 'text-red-500'}`}>{trade.result.toUpperCase()}</td>
                        </tr>
                    ))}
                </tbody>
            </table>

            {/* FOOTER */}
            <div className="mt-12 pt-6 border-t border-[rgba(255,255,255,0.05)] text-center text-gray-500 text-[10px]">
                <p>Generated by ENTJournal · Track. Reflect. Improve.</p>
                <p className="text-[#00C853]">entjournalv1.vercel.app</p>
            </div>
        </div>
    );
};
